### PR TITLE
Kopia UI: support for multiple repositories + portability

### LINKED ISSUE #368: feature request: make kopia UI portable
Hi,
is it possible to make Kopia UI portable? so we can put it an usb with it's config files.
thank  you

### LINKED ISSUE #382: Feature request:  add an option to use more than one repository at the same time
Hi,
I hope you can add an option to use more that one repository at the same time, or gave an option to switch between repos easily, maybe adding a list of used repos in Kopia UI 
I could not find any way to connect for example to my local repo and my server repo at the same time. I have to disconnect every time and put the password to connect , and do it again to come back. this make it a hard experience.

Thank you.

### PR DESCRIPTION
**Pull request by jkowalski**
This is a major rewrite of the app/ codebase which changes
how configuration for repositories is maintained and how it flows
through the component hierarchy.

Portable mode is enabled by creating 'repositories' subdirectory before
launching the app.

on macOS:

```
  <parent>/KopiaUI.app
  <parent>/repositories/
```

On Windows, option #1 - nested directory
```
  <parent>\KopiaUI.exe
  <parent>\repositories\
```

On Windows, option #2 - parallel directory
```
  <parent>\some-dir\KopiaUI.exe
  <parent>\repositories\
```

In portable mode, repositories will have 'cache' and 'logs' nested in it.

Fixes #368 
Fixes #382

### CODE REVIEW

**Comment by jkowalski** [comment]
@badrelmers would you be able to give it a try?

**Comment by badrelmers** [comment]
@jkowalski 
Hi, sorry for being late.

I tested the last portable version : [link](https://github.com/kopia/kopia-ui-release/releases/download/20200420.0.83003/KopiaUI-20200420.0.83003-win.zip)

1. It is not fully portable, I have to configure Kopia UI by changing the "Override Configuration File" from the GUI to make it fully portable. if I do not do this step then Kopia UI saves its config files in %APPDATA%.

2. even after doing step (1.), some files are still saved in %APPDATA%, but they seems to be just cache files, which are not important (I hope I m not wrong). 

is it possible to make Kopia UI auto create that "Configuration File", this is the expected behavior of a portable app, it have to be portable without the need to configure it to make it portable.

except this (1.) everything works fine. Thank you very much for this.

**Comment by jkowalski** [comment]
Can you file a new issue for 1) ? I'm not sure if there's much that can be done about 2) because Electron-based apps need to have cache files somewhere.

**Comment by badrelmers** [comment]
done https://github.com/kopia/kopia/issues/428
for 2) it can be solved by running Kopia UI with `KopiaUI.exe --user-data-dir="F:\path\to\cachefolder"` anyway, and maybe mention that in the doc for the paranoid users.

**Pull request merged**
