### PR TITLE
feat(ui): Save page size

### LINKED ISSUE #2060: Kopia UI: Table pagination disappears after increasing page size
The page size is initially 10.

I have 14 tasks.

When I change the page size to 20, all items become visible, but **the pagination controls disappear.**

kopia-table-pagination-disappears

I expected the pagination controls to remain visible so I could reduce the page size back down to 10 (if I wanted to).

### PR DESCRIPTION
**Pull request by phidevz**
Also fixes #2060.

In general, this PR provides a server API to save the pageSize as UI preference. 
Other changes will be made in kopia/htmlui.

### CODE REVIEW

**Review by jkowalski — APPROVED** [review]

**Comment by jkowalski** [comment]
Thanks for the contribution!

**Comment by basldfalksjdf** [comment]
I just tested latest KopiaUI, and it is saving page size option during each instance of having a KopiaUI window open, but if I close KopiaUI and reopen it, the page size defaults back to 10.

**Comment by basldfalksjdf** [comment]
Another bug: clicking the Kopia logo in KopiaUI resets the page size.

**Comment by basldfalksjdf** [comment]
Not sure if this error has to do with these bugs: `2022-07-04T15:40:48.871782Z WARN kopia/server missing CSRF token for /api/v1/ui-preferences`

**Pull request merged**
