### PR TITLE
Improve ignore logic.

### PR DESCRIPTION
**Pull request by darkdragon-001**
- Add test cases for absolute patterns
- Support globs for absolute patterns

See https://github.com/kopia/kopia/issues/492#issuecomment-662842450 for details.

### CODE REVIEW

**Comment by x80486** [comment]
I'm trying to come up with a `.kopiaignore` file that fits my needs, and so far, it's not "including on an exclusion". This is my example:

```shell
Desktop/
Workshop/**/.idea/
Workshop/**/.terraform/
Workshop/**/node_modules/
Workshop/**/*.iml/
Workshop/**/*.ipr/
.cache/
.config/
.gradle/
.gradle-kotlin-dsl/
.java/
.local/
.m2/
.npm/
.var/
.bash_history
.node_repl_history
# The previous lines work as expected, but as soon as I add the following lines, everything is excluded
!Workshop/**/terraform.tfstate.d/
!Workshop/**/terraform.tfstate
!.config/Cryptomator/
!.config/JetBrains/**/keymaps/
!.config/JetBrains/**/idea.key
!.local/share/bash-completion/
!.local/share/now/
```

Are you addressing something like this in this Pull Request?

**Comment by darkdragon-001** [comment]
@x80486 Just pull this code, add your test cases and compile & test :wink: 

Previously *all* globs where not processed when a `/` was within pattern. So some of your patterns should work.

Quoting from the [pattern format definition](https://git-scm.com/docs/gitignore#_pattern_format)

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash ("\") in front of the first "!" for patterns that begin with a literal "!", for example, "\!important!.txt".

at least some of your test cases are not supported.

**Comment by x80486** [comment]
OK, I'll wait for this release, but I can guarantee you with `kopia-0.5.2`, what I have there doesn't work :no_good_man: ...and that's exactly what I use with `borgbackup`.

**Comment by darkdragon-001** [comment]
@x80486 It would still be helpful if you construct some test cases (positive and negative ones) like I did: https://github.com/kopia/kopia/pull/496/files#diff-8527ab4f16d218759fedf0987ace90f7.

This are just short one-liners for you, but help a lot in keeping this module stable ove time.

**Comment by jkowalski** [comment]
ok, I think we're ready to merge this, let's just make sure linter is clean

**Comment by 8176135** [comment]
Perhaps merge this PR first, and then work on the improvements for unignoring files later?

The current ignore syntax on master doesn't work for any paths starting with /, which is quite commonly used in most .gitignore files, and this branch works for that, which is a major improvement.

**Comment by darkdragon-001** [comment]
> Can you also add couple smoke tests in `ignorefs_test.go`, which is one layer above.

@jkowalski I added such tests.

**Comment by jkowalski** [comment]
@darkdragon-001 can you update the branch and re-push? I'll be happy to take a look and we can merge soon then work on additional cases.

**Comment by jkowalski** [comment]
LGTM, Thanks!

**Pull request merged**
