### PR TITLE
feat(repository): allow configuring auto compaction count

### PR DESCRIPTION
**Pull request by vkamra**
Adds a manager option to configure the threshold after which auto compaction kicks in.

This is useful when there are large number of concurrent writers in a repository and the default threshold
causes auto-compaction to thrash.

In a follow-up PR - will allow configuring this in repository open.

### CODE REVIEW

**Review by julio-lopez — COMMENTED** [review]
+1: LG 👍

@jkowalski may have comments, so letting it to him to approve.

**Comment by jkowalski** [comment]
LGTM as-is, but i'd like to rethink the whole auto-compaction business and perhaps move it to maintenance. I don't want to block what you're trying to do here, so let's work on maintenance separately.

**Review by jkowalski — APPROVED** [review]

**Comment by vkamra** [comment]
> LGTM as-is, but i'd like to rethink the whole auto-compaction business and perhaps move it to maintenance. I don't want to block what you're trying to do here, so let's work on maintenance separately.

Agree with moving to maintenance. @ashmrtn and I were looking into this with our workload (lots of concurrent writers) and the approach we've been discussing is leveraging the flag here to disable compaction during backup and let maintenance run with default parameters.

Maintenance does end up triggering manifest compaction today (indirectly) as a result of [this](https://github.com/kopia/kopia/blob/master/repo/maintenance/maintenance_params.go#L117) call

**Comment by jkowalski** [comment]
yeah, we should make it explicit, so that only maintenance ever calls it.

**Comment by julio-lopez** [comment]
@vkamra can you rebase please? We are not able to do it.

**Comment by vkamra** [comment]
> @vkamra can you rebase please? We are not able to do it.

Yep - I got this. Will push shortly.

**Review by julio-lopez — APPROVED** [review]

**Comment by julio-lopez** [comment]
Will fix linter annotation issue in a sec

**Pull request merged**
