### PR TITLE
style(general): new kopia icons

### PR DESCRIPTION
**Pull request by s-h-a-r-d**
changed kopia icons to the new ones as agreed on slack: https://kopia.slack.com/archives/CH7R8L2KD/p1662751293687799

### CODE REVIEW

**Comment by jkowalski** [comment]
could you also make a white version with black outline?

**Comment by s-h-a-r-d** [comment]
sure, which ones would that replace?

**Comment by jkowalski** [comment]
kopia-flat-outline.svg

**Comment by s-h-a-r-d** [comment]
Ok, I edited the file through github. Not sure if it is already part of this PR or if a completely new PR needs to be done.

**Comment by jkowalski** [comment]
Ok, i finally got to trying the icons. 

Looks like there's a bunch more that needs to change. Can you also update all *.png, *.ico and *.icns images under `app` ?

To try `make kopia-ui` should build an executable.

**Comment by jkowalski** [comment]
Icons based on this design are now merged - #2451.

**Pull request closed without merging**
