### PR TITLE
Add a way to execute S3 storage test on AWS

### PR DESCRIPTION
**Pull request by PrasadG193**
- Add a way to execute S3 storage test on AWS
- Create kopia bucket and user with unique ID on minio
- Create AWS bucket before running tests

### CODE REVIEW

**Comment by PrasadG193** [comment]
| Test  | Description |  Env vars need to be set |
|-------|-------------|--------------------------|
| TestS3StorageMinio  | Test S3 blob storage implementation with AccessID and SecretKey on MinIO (play.minio.io) | NA  |
| TestS3StorageMinioSTS  | Test S3 blob storage implementation with Session Token on MinIO (play.minio.io) | NA  |
| TestS3StorageAWS  | Test S3 blob storage implementation with AccessID and SecretKey on AWS | KOPIA_S3_TEST_BUCKET<br> KOPIA_S3_TEST_ACCESS_KEY_ID<br> KOPIA_S3_TEST_SECRET_ACCESS_KEY<br> KOPIA_S3_TEST_REGION |
| TestS3StorageAWSSTS  | Test S3 blob storage implementation with Session Token on AWS | KOPIA_S3_TEST_BUCKET<br> KOPIA_S3_TEST_STS_ACCESS_KEY_ID<br> KOPIA_S3_TEST_STS_SECRET_ACCESS_KEY<br> KOPIA_S3_TEST_SESSION_TOKEN<br> KOPIA_S3_TEST_REGION<br>  |

**Comment by julio-lopez** [comment]
Also, Fixes #254

**Comment by julio-lopez** [comment]
@jkowalski PTAL

**Comment by jkowalski** [comment]
Thanks. This looks great.

**Pull request merged**
