### PR TITLE
Update _index.md: old link redirects to sales page

### PR DESCRIPTION
**Pull request by triatic**

### CODE REVIEW

**Review by lupusA — COMMENTED** [review]
We should probably add the benchmark on our site and not refer to the web archive imo. 
What do you think?

**Comment by triatic** [comment]
> We should probably add the benchmark on our site and not refer to the web archive imo.

Linking to an external source gives some assurance of trust/independence. Plus there may be copyright issues around copying the benchmark to another site (permission to re-publish would be needed).

**Comment by lupusA** [comment]
> > We should probably add the benchmark on our site and not refer to the web archive imo.
> 
> Linking to an external source gives some assurance of trust/independence. Plus there may be copyright issues around copying the benchmark to another site (permission to re-publish would be needed).

We should ask about getting the permission then. Otherwise, we will have dead links here and there all the time :-)

**Comment by triatic** [comment]
> We should ask about getting the permission then. Otherwise, we will have dead links here and there all the time :-)

Ok, but that might take some time. Accepting the PR would solve things before that is achieved.

**Pull request merged**
