### PR TITLE
refactor(repository): Following up code adjustment for on-use-builder

### PR DESCRIPTION
**Pull request by Lyndon-Li**
A following up PR of #4139 to address comment https://github.com/kopia/kopia/pull/4139#discussion_r1793663722 and https://github.com/kopia/kopia/pull/4139#discussion_r1793665281.

### CODE REVIEW

**Comment by Lyndon-Li** [comment]
https://github.com/kopia/kopia/actions/runs/11285623924/job/31389954180?pr=4167
This CI error seems not to be caused by this PR.

**Comment by Lyndon-Li** [comment]
@jkowalski
Could you help to check this CI failure https://github.com/kopia/kopia/actions/runs/11285623924/job/31389954180?pr=4167?
It seems timeout happened for test `TestByteRepresentation`, but I didn't reproduce it locally.
And the timeout of snapshot creation doesn't look related to the code changes of this PR.

**Comment by jkowalski** [comment]
I honestly have no idea why it failed so many times, I don't think it's related to your change at all. Thanks for the fixes!

**Comment by Lyndon-Li** [comment]
@jkowalski Thanks for reviewing this PR!

**Pull request merged**
